### ISSUE TITLE
im also looking for Permanently disable links

### ISSUE THREAD

**Issue by astersalvage** [fabiosangregorio/links-disabler#4] opened 2020-11-16 18:00 UTC
love the progam ..... im also looking for Permanently disable links,

**Comment by fabiosangregorio** [comment] 2020-11-20 14:37
Hi @astersalvage, this is a duplicate of #3 , so I'm gonna close it. I hope I can get around implementing it soon.

**Closed as completed by fabiosangregorio** 2020-11-20 14:37 UTC
